KittyRental/config/routes.rb
Rails.application.routes.draw do
  resources :cats

  resources :cat_rental_requests, only: [:create, :new]

  resources :cat_rental_requests do
    post :approve, on: :member
    post :deny, on: :member
  end

end

KittyRental/app/models/cat.rb
class Cat < ActiveRecord::Base
  CAT_COLORS = %w(black white gray orange brown pink)
  validates :color, presence: true, inclusion: CAT_COLORS
  validates :sex, presence: true, inclusion: %w(M F)
  validates :birth_date, :name, presence: true

  has_many :rental_requests, class_name: "CatRentalRequest", dependent: :destroy

  def age
    age = Date.today.year - self.birth_date.year
  end
end

KittyRental/app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base
    RENTAL_STATUS = %w(PENDING APPROVED DENIED)

    belongs_to :cat

    validates :cat_id, :start_date, :end_date, :status, presence: true
    validates :status, inclusion: RENTAL_STATUS

    validate :start_must_come_before_end
    validate :does_not_overlap_approved_request

    def approve!
      CatRentalRequest.transaction do
        self.status = "APPROVED"
        self.save! # save the model

        # when we approve this request, we reject all other overlapping
        # requests for this cat.
        overlapping_pending_requests.update_all(status: 'DENIED') ## update_all updates all records
      end
    end

    def denied?
      self.status == "DENIED"
    end

    def deny!
      self.status = "DENIED"
      self.save!
    end

    def pending?
      self.status == "PENDING"
    end

    private

    def overlapping_requests
      CatRentalRequest
        .where.not(id: self.id)
        .where(cat_id: cat_id)
        .where(<<-SQL, start_date: start_date, end_date: end_date)
           NOT( (start_date > :end_date) OR (end_date < :start_date) )
        SQL
    end

    def overlapping_approved_requests
      overlapping_requests.where("status = 'APPROVED'")
    end

    def overlapping_pending_requests
      overlapping_requests.where("status = 'PENDING'")
    end

    def does_not_overlap_approved_request
      return if self.denied?

      unless overlapping_approved_requests.empty?
        errors[:base] <<
          "Request conflicts with existing approved request"
      end
    end

    def start_must_come_before_end
      return if start_date < end_date
      errors[:start_date] << "must come before end date"
      errors[:end_date] << "must come after start date"
    end
  end

KittyRental/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
#  protect_from_forgery with: :exception
end

KittyRental/app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController

  def approve 
    current_cat_rental_request.approve!
    redirect_to cat_url(current_cat)
  end

  def deny
    current_cat_rental_request.deny!
    redirect_to cat_url(current_cat)
  end


  def create
    @rental_request = CatRentalRequest.new(request_params)
    if @rental_request.save
      redirect_to cat_url(@rental_request.cat)
    else
      flash.now[:errors] = @rental_request.errors.full_messages
      render :new
    end
  end


  def new
    @rental_request = CatRentalRequest.new
  end

  private
  def current_cat_rental_request
    @rental_request ||=
      CatRentalRequest.includes(:cat).find(params[:id])
  end

  def current_cat
    current_cat_rental_request.cat
  end

  def request_params
    params.require(:cat_rental_request).permit(:cat_id, :end_date, :start_date, :status)
  end
end

KittyRental/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  #[:index, :show, :create, :update, :destroy, :edit]

  def index #good
    @cats = Cat.all #Instance variables set in the controller will be made available to the view template (specified with render)
    render :index #index.html.erb
  end

  def new
    @cat = Cat.new #Instance variables set in the controller will be made available to the view template
    render :new
  end

  def show #good
    @cat = Cat.find(params[:id])
    render :show #show.html.erb
  end

  def create
    @cat = Cat.new(cat_params)

    if @cat.save
      redirect_to cat_url(@cat) #cat_url is a routing helper method
    else
      flash.now[:errors] = @cat.errors.full_messages
      render :new
    end
  end

  def update
    @cat = Cat.find(params[:id])

    if @cat.update(cat_params)
      redirect_to cat_url(@cat) #cat_url is a routing helper method
    else
      flash.now[:errors] = @cat.errors.full_messages
      render :edit
    end
  end

  def edit
    @cat = Cat.find(params[:id])
    render :edit #edit.html.erb
  end

  def destroy
    @cat = Cat.find(params[:id])
    @cat.destroy
    redirect_to cats_url # routing helper method for building url with all cats
  end

  private
  def cat_params #good
    params.require(:cat).permit(:birth_date, :name, :sex, :color, :description)
  end
end

KittyRental/app/helpers/application_helper.rb
module ApplicationHelper
end

KittyRental/app/helpers/cat_rental_requests_helper.rb
module CatRentalRequestsHelper
end

KittyRental/app/helpers/cats_helper.rb
module CatsHelper
end

KittyRental/app/views/cat_rental_requests/_errors.html.erb
<% if flash[:errors] %>
  <ul>
  <% flash[:errors].each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
<% end %>

KittyRental/app/views/cat_rental_requests/new.html.erb
<html>

<body background="http://24.media.tumblr.com/8210fd413c5ce209678ef82d65731443/tumblr_mjphnqLpNy1s5jjtzo1_400.gif">
  <%= render "errors" %>
  <%= link_to "<< Back to all cats", cats_url %>

<center><h2>Rental Request Form</h2>
  <form action="<%= cat_rental_requests_url %>" method="post">

<!-- CHOOSE CAT -->
  <label for="cat_selection">Select cat:</label>
  <select name="cat_rental_request[cat_id]" id="cat_selection">
      <option>Select cat</option>
    <% Cat.all.each do |cat| %>
      <option value="<%= cat.id %>"><%= cat.name %></option>
          <% end %>
  </select>
  <br>
<!-- CHOOSE START AND END DATE -->
  Select the time period you would like to rent this cat:
<br>
  <label for="rental_start_date">Start date:</label>
  <input type="date" name="cat_rental_request[start_date]" id="rental_start_date">
<br>
  <label for="rental_end_date">End date:</label>
  <input type="date" name="cat_rental_request[end_date]" id="rental_end_date">
<br>
<input type="submit" value="SUBMIT RENTAL REQUEST">
</form></center>

</body>
</html>
<!--



Add a create action, of course.
Edit the cat show page to show existing requests

Just show the start, end dates.

Use order to sort them by start_date -->

KittyRental/app/views/cats/_form.html.erb
<html>
<% action= cat.persisted? ? cat_url(cat) : cats_url %>
<% method= cat.persisted? ? :patch : :post %>

<center><form action ="<%= action %>" method = "post">
  <input type="hidden" name="_method" value="<%= method %>">

<!-- NAME  -->
  <label for="cat_name">Cat's name:</label>
    <input type="text" id="cat_name" name="cat[name]" value="<%= cat.name %>" placeholder="Enter cat name here...">

<br>
<!-- GENDER -->
  <label for="cat_sex">Cat's gender:</label>
    Male<input type="radio" id="cat_sex" name="cat[sex]" value="M"
    <%= cat.sex == "M" ? "checked" : "" %>>
    Female<input type="radio" id="cat_sex" name="cat[sex]" value="F"
    <%= cat.sex == "F" ? "checked" : "" %>>

<br>
<!-- COLOR -->
  <label for="cat_color">Color</label>
  <select name="cat[color]" id="cat_color">
      <option>Select color</option>
    <% Cat::CAT_COLORS.each do |color| %>
      <option
      <%= cat.color == color ? "selected" : "" %>
        value="<%= color %>">
        <%= color.upcase %></option>

          <% end %>
  </select>

<br>
<!-- BIRTH DATE  -->
<label for="cat_birth_date">Cat's birth date</label>
<input type="date" name="cat[birth_date]" id="cat_birth_date" value="<%= cat.birth_date %>"><br>

<!-- DESCRIPTION  -->
  Cat's description:<br>

    <textarea name="cat[description]" cols="60" rows="10" placeholder="Describe your cat here..."><%= cat.description %></textarea>
<br>
<% submit_text = (cat.persisted? ? 'Update' : 'Create') + ' cat!' %>
<input type="submit" value="<%= submit_text %>">
</form><center>



</html>

KittyRental/app/views/cats/edit.html.erb
<title> ✍ Edit <%= @cat.name %>'s profile</title>
<%= link_to "<< Back to all cats", cats_url %>
  <body style="background-color:#f0e6ff;">

<center><h1 style="color:purple;">✍ Edit <%= @cat.name %>'s profile</h1></center>
    <%= render "errors" %>
    <%= render "form", cat: @cat %>
  </body>

KittyRental/app/views/cats/index.html.erb
<html>
  <body background="http://data.whicdn.com/images/225089317/large.gif">>

  <style>
    li{ list-style-type: none;
      }
  </style>
  <title>99 Cats - for all your cat renting needs</title>

  <center><h1 style="color:purple;">99 Cats - Book Your Favorite Cat 2Day!</h1></center>

  <nav>
  <center><h2 style="color:purple">🐱 Available Cats 🐱</h2>
  <ul><% @cats.each do |cat| %>
    <li><%= link_to "#{cat.name}", cat_url(cat) %></li>
        <% end %>
  </ul>
  </center>
  </nav>
  <br>
  <center><%= link_to "➕ Add Cat!", new_cat_url %></center>
</body>
</html>

KittyRental/app/views/cats/new.html.erb
<title>Create new cat %></title>
<%= link_to "<< Back to all cats", cats_url %>
  <body style="background-color:#f0e6ff;">
<center><h1 style="color:purple;">Create new cat</h1></center>
    <%= render "errors" %>
  <%= render "form", cat: @cat %>
</body>

KittyRental/app/views/cats/show.html.erb
<html>
<head>
  <title><%= @cat.name %>'s Profile</title>
<%= link_to "<< Back to all cats", cats_url %>
<center><%= link_to "✍ Edit cat's profile", edit_cat_url(@cat) %></center>
<center><%= link_to "💖 Submit rental request", new_cat_rental_request_url(@rental_request) %></center>

  <center><h1 style="color:purple;"><%= @cat.name %>'s Profile</h1></center>
  <center><img src="http://i.imgur.com/Y8PIcM4.gif" width="370" height="auto" border="1px"></center>

  <style>
  table, th, td {
      border: 1px solid purple;
      border-collapse: collapse;
    background-color: #e6e6ff}
  </style>
  </head>

<center><table cellpadding="15">
  <tr>
    <th>Name:</th>
    <td><%= @cat.name%></td>
  </tr>

  <tr>
    <th>Age:</th>
    <td><%= @cat.age %></td>
  </tr>

  <tr>
    <th>Color:</th>
    <td><%= @cat.color %></td>
  </tr>

  <tr>
    <th>Sex:</th>
    <td><%= @cat.sex %></td>
  </tr>

  <tr>
    <th>Description:</th>
    <td><%= @cat.description %></td>
  </tr>
</table></center>

<center><h1>Rental Requests for <%= @cat.name %></h1>
  <table cellpadding="15">
    <tr>
      <th>Start date</th>
      <th>End date</th>
      <th>Rental request status</th>
    </tr>
  <% @cat.rental_requests.order("start_date").each do |rental_request| %>
        <tr>
          <td><%= rental_request.start_date %></td>
          <td><%= rental_request.end_date %></td>
          <td><% if rental_request.pending? %>
                 <%= button_to "Approve", approve_cat_rental_request_url(rental_request) %>
                 <%= button_to "Deny", deny_cat_rental_request_url(rental_request) %>
             <% else %>
               <%= rental_request.status %>
             <% end %></td>
        </tr>
      <% end %>
      <!-- On the Cat show page, make a button to approve or deny a cat request.
      Only show these buttons if a request is pending.
      You may want to add a convenient CatRentalRequest#pending? method. -->
  </table>

</center>

</html>

KittyRental/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KittyRental</title>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>